### ISSUE TITLE
Consider changing log impl poll callback parameters

### ISSUE THREAD

**Issue by tezc** [RedisLabs/raft#135]
Currently, defined as  
```
int (*poll) (void *log, raft_index_t first_idx);
```

It might be useful to change as 

```
int (*poll) (void *log, raft_term_t prev_term, raft_index_t prev_idx);
```

So, log impl can store prev term and prev index for validation purposes.

**Comment by fadidahanna** [comment]
https://redislabs.atlassian.net/browse/RR-305?atlOrigin=eyJpIjoiODE3MTRiMzE4ZGI1NDY2MDg0YmZkOWEyYWU3MDk1ZmIiLCJwIjoiaiJ9
