### ISSUE TITLE
Improve unit tests framework

### ISSUE THREAD

**Issue by yossigo** [RedisLabs/raft#22]
The unit tests framework is not very friendly at the moment, making it more difficult to create tests for simple flows.

There are different ways to address that --
* Implement some helpers based on the current unit test framework
* Use some of the Virtraft CFFI work and come up with a Python-based test framework
* Other options?

**Comment by fadidahanna** [comment]
JIRA ticket: https://redislabs.atlassian.net/browse/RR-306
