### ISSUE TITLE
potential race condition in removing/adding same node?

### ISSUE THREAD

**Issue by skygragon** [RedisLabs/raft#73]
say we remove node the add it back as non-voting, seems there would be race condition to cause a crash?

1. append log "remove node A"
2. append log "add non-voting node A" => new node memory
3. later apply log "remove node A" => free node memory
4. apply log "add non-voting node A" => update node memory (oops!)

**Comment by tezc** [comment]
@skygragon

Only one voting change is allowed until first one is committed. So, once you appendded removal, you wait until it's applied to append another add or remove. So, scenario above cannot happen. https://github.com/RedisLabs/raft/blob/e8096ed113d657182d106828482f01a7fdc3d4b5/src/raft_server.c#L1127

**Comment by skygragon** [comment]
ok, seems there is a bit changes since my last pull

![image](https://user-images.githubusercontent.com/1295096/142383464-5a355e7b-b10d-42a9-9822-f67e1781a1e0.png)

![image](https://user-images.githubusercontent.com/1295096/142383548-4f875777-3a29-4d04-a450-ff0939fcf3bb.png)

the latest code has no "demote" step?

**Comment by tezc** [comment]
@skygragon  Yes, demote step adds complexity to the code so we've deleted it. Library users can now manually trigger "leader transfer operation and then remove the node" instead of automatic "demote + remove".

**Comment by skygragon** [comment]
@tezc thanks，I will read this change to learn the detail.

but as far as I understand, the "demote" step is simply used as the 1st part of a graceful deleting to skip voting. still wondering why it's related to leader transfer?

**Comment by tezc** [comment]
@skygragon Sorry, demote had another/mixed meaning in one point of time in the code base, confused me for a while. Please dismiss my comment about leadership change. 

I see in older versions, it was purely an operation to set a node as "non-voting". Even then, removing a node does not actually need separate demote operation. Once you append a removal entry for a node, that node becomes non-voting immediately (in the code, node is set as "inactive" until entry is committed).  Once entry is committed, node is removed forever. So, demote is inherent to remove operation according to Raft. No need to trigger it separately.

**Comment by skygragon** [comment]
@tezc thanks a lot~
