### ISSUE TITLE
Add callbacks for handling entry state on append (and removal from log)

### ISSUE THREAD

**Issue by sjpotter** [RedisLabs/raft#74]
Currently, raft_append_entry() can handle cluster config entries specially (i.e. they get handled at append time).  However, if a user defines their own entries, there isn't a good way to do the same thing if they want to handle state on append.

If we view this as a valid idea, we would want to create callbacks that mirror the built in calls for adding/removing cfg change entries and have them called similiarly to the cfg_change functions in the same places.  (namely, raft_delete_entry_from_idx()/raft_append_entry()

might also want a similiar callback for use with raft_apply_entry()?

my motivation about this is in regards to if we wanted to implement 2 phase commits for transaction oriented operations, where would want to know before we apply the entry that the second phase has been committed to the cluster.

thoughts?

**Comment by sjpotter** [comment]
example api

```
void handle_append_entry(raft_server_t * raft_ctx, void *user_data, raft_entry_t *entry, raft_index_t idx);
void handle_remove_entry(raft_server_t * raft_ctx, void *user_data, raft_entry_t *entry, raft_index_t idx);
```

the handle_append_entry() calls doesn't have direct access to idx, for instance, the current code needs to call raft_get_current_idx() for voting changes recording.  a related thought might be that 

```
    int e = me->log_impl->append(me->log, ety);
    if (e < 0)
        return e;
```

shouldn't return 0, but the new/current idx, if not an error.  just a thought.

**Comment by fadidahanna** [comment]
Issue is not relevant any more.
