### ISSUE TITLE
Enable raft_apply_entry() to fail in a delayed manner

### ISSUE THREAD

**Issue by sjpotter** [RedisLabs/raft#75]
Currently, raft_apply_entry can either succeed or effectively fail terminally.  

note for instance the current code

```
    me->last_applied_idx++;
    if (me->cb.applylog)
    {
        int e = me->cb.applylog(me_, me->udata, ety, me->last_applied_idx);
        if (RAFT_ERR_SHUTDOWN == e) {
            raft_entry_release(ety);
            return RAFT_ERR_SHUTDOWN;
        }
    }
```
even though it only considers a RAFT_ERR_SHUTDOWN to be a terminal error, it practice, any error returned from cb.applylog() would break the system as it considered the entry applied (incremented idx) before it applied it.

so arguably the idx increment should be moved to after success, but I'm wondering if we should make it even more explicit to distinguish between different types of errors, where some errors are terminal, and some are "try again later".

**Comment by fadidahanna** [comment]
Issue was already solved by adding an assert to prevent this state: https://github.com/RedisLabs/raft/blob/a634de6f81e1d774ce95e3acd62aef349ce6e521/src/raft_server.c#L1314
