### ISSUE TITLE
raft_poll_entry bug?

### ISSUE THREAD

**Issue by skygragon** [RedisLabs/raft#78]
![image](https://user-images.githubusercontent.com/1295096/147737022-0e0382a5-026c-4f7d-a62f-eff6d1ec8aa2.png)

you see log->poll(idx) will remove all committed entries "before" idx, so if here we use first_idx, there will be no entry deleted at all?

**Comment by freecw** [comment]
I was also puzzled by this.

**Comment by tezc** [comment]
```c
    /** Remove entries from the start of the log, as necessary when compacting
     * the log and deleting the oldest entries.
     *
     * @param[in] first_idx Index of first entry to be left in log.
     * @return
     *  0 on success;
     *  -1 on error (e.g. log is empty).
     */
    int (*poll) (void *log, raft_index_t first_idx);
```

It will remove entries **after** idx I guess, not before.

**Comment by skygragon** [comment]
nope，Remove entries from the start of the log。。。。 should be any logs before first_idx :)

**Comment by tezc** [comment]
Ah you're right, I was confused too :)  

Yes, this function won't remove an entry. I see we are not using it anywhere, so didn't see a problem so far. There are some usages in tests but it just returns success even it doesn't remove an entry.
