### ISSUE TITLE
logic changed a bit in raft_set_snapshot_metadata()?

### ISSUE THREAD

**Issue by skygragon** [RedisLabs/raft#79]
![image](https://user-images.githubusercontent.com/1295096/147812272-8ef87173-2e83-47d5-bf76-5b2e9366c557.png)

saved_snapshot_last_term was used to remember last snapshot meta, thus we could revert back in snapshot cancel. then if here is using next_snapshot_last_term instead, maybe lines 273~274 are not quite correct and make a potential bug left?

**Comment by tezc** [comment]
Yes, this is not necessary but it looks harmless. Snapshot API needs some refactoring IMHO, so, maybe we can fix this one as well.
