### ISSUE TITLE
question about read index?

### ISSUE THREAD

**Issue by skygragon** [RedisLabs/raft#80]
![image](https://user-images.githubusercontent.com/1295096/148374831-b2d9c382-badd-466c-9aa6-a3e2d0532d16.png)

why using current log index instead of commit idx?

**Comment by tezc** [comment]
To process a read request, previous entries must be applied to the state machine. So, you have to wait until it's applied.
e.g initially x = 0;
1- Append to the log : write x=1
2- Queue read request x

In the second step, you must read x=1, so, you have to wait until write operation is applied to the state machine.

**Comment by skygragon** [comment]
Yes we have to wait until "the log" has been applied. But "the log" should be  the "current already committed", not "raft_get_current_idx()". You see current_idx would include those pending logs that not meet majority yet. So it's no need to wait for them applied, only those already committed is good enough.

**Comment by tezc** [comment]
> You see current_idx would include those pending logs that not meet majority yet. So it's no need to wait for them applied, only those already committed is good enough.

That would violate linearizability I believe. If you don't wait, you won't see the effect of some of the previous operations. Take a look at the example above, you send two operations without waiting response of the first. 

1- "write x=1" in the log, waiting to be replicated.
2- "read x". 

Now, if you don't wait the first operation until it's applied, you'll read previous value of x. This is probably not what we want.

**Comment by skygragon** [comment]
well if the 1st "write x=1" is waiting for replicating to majority, this write request is still under processing and no result is guaranteed to client at this moment, which doesn't violate linearizability IMHO (linearizability only requires the subsequent read MUST see the new value ONCE the previous write is successful to client)

**Comment by tezc** [comment]
Thinking again, you're right. If the write operation is not completed, no need to wait for it to be "linearizable".  Still, for the above example, the result will be counter-intuitive for the client. So, I rather keep the code the way it is. Good part is, in practice, both solution would perform same. We need to send a round of appendentries for the new read request (to verify we are still the leader). That means, either we've already sent appendentries for the entries in the log that are waiting to be committed or we'll send them with the current appendentries round. So, we'll commit & apply entries either before or at the same time we confirm we are still the leader for this new read request. (I assume stable connections, no out of order delivery, basically I'm assuming TCP).
