### ISSUE TITLE
question about raft_get_first_entry_idx

### ISSUE THREAD

**Issue by freecw** [RedisLabs/raft#82]
I am confused with raft_get_first_entry_idx() and raft_log_internal_impl.first_index, 

it seems raft_log_internal_impl.first_index is larger than raft_get_first_entry_idx() by 1. So what is the intention of implementing raft_get_first_entry_idx()?

```c
raft_index_t raft_get_first_entry_idx(raft_server_t* me_)
{
    raft_server_private_t* me = (raft_server_private_t*)me_;

    assert(0 < raft_get_current_idx(me_));

    if (me->snapshot_last_idx == 0)
        return 1;

    return me->snapshot_last_idx;
}

static raft_index_t __log_first_idx(void *log)
{
    return log_get_base(log) + 1;
}
```

**Comment by tezc** [comment]
Probably, only for printing some debugging info? Log index is always one more than snapshot last index, so it's normal. I don't see any use case other than debugging/testing.
