### ISSUE TITLE
Raft library interface cleanup

### ISSUE THREAD

**Issue by yossigo** [RedisLabs/raft#97]
API should be stabilized to enable NGC usage.

**Comment by fadidahanna** [comment]
https://github.com/tezc/redisraft/blob/6bb34f122f6e86c648fb9386df3c62b9916ca4eb/src/snapshot.c#L69
See raft_ library usage inside writeSnapshotFile() and readSnapshotFile()
This is currently how we should store configuration and reconfigure libraft after loading a snapshot
sharing with you just to give you an idea how complex it is
A good library would hide these. It would give you a buffer which includes node configuration, then you would pass that buffer back to the library after snapshot load. So, library can configure itself.

**Comment by fadidahanna** [comment]
we also need to go over callbacks (some of them can be combined/deleted) + need to decide if we can move some configs into libraft

Other minor issue is, libraft is over-commented
Lots of words in the header, mostly they don't tell anything
 * @param[in] raft The Raft server making this callback
 * @param[in] user_data User data that is passed from Raft server
Each function has these lines, I don't see any value in these. It feels unnecessary
